name: code-ranker
on:
  pull_request:
    paths:
      - '**/*.rs'
      - '**/Cargo.toml'
      - 'Cargo.lock'
      - 'rust-toolchain.toml'
      - '.cargo/**'
      - '!**/tests/**'
      - '!testing/**'
      - '!**/*.md'
      - '!docs/**'
      - '!guidelines/**'
  push:
    paths:
      - '**/*.rs'
      - '**/Cargo.toml'
      - 'Cargo.lock'
      - 'rust-toolchain.toml'
      - '.cargo/**'
      - '!**/tests/**'
      - '!testing/**'
      - '!**/*.md'
      - '!docs/**'
      - '!guidelines/**'
jobs:
  code-ranker:
    uses: code-ranker-com/actions/.github/workflows/report.yml@v1
    permissions:
      id-token: write
      contents: read
      pull-requests: write
      security-events: write
